# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e29e61fc8f7ed0d060767372843ed48af9ce20d93bdea13e330213d9a7f44037eb9b01e24766173bcc5c301c0a8658502fd4b35e6c3a13bf6d0f96402c6e0c

test:
  secret_key_base: e34b7f18e9123738f79ec2d039e13df28a9efe40f689641364f10aa3c2a853709e7d121a9013e5b45020055ba83bf94b904225beb60528e760042fe0aaf3eab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
